language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - yarn test:coverage

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage --coverageReporters=text-lcov | coveralls
